name: Welcome New Contributors

on:
  pull_request:
     types: [opened]

jobs:
  greet:
      runs-on: ubuntu-latest
      steps:
        - name: Greet the contributor
          uses: actions/first-interaction@v1
          with:
            repo-token: ${{f secrets.GITHUB TOKEN }}
            pr-message: "# Thank you for your first pull request! We appreciate your contri"
